name: ganga
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  intl: ^0.17.0
  async: ^2.8.2
  rxdart: ^0.27.5
  readmore: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  json_serializable: ^6.3.2
  json_annotation: ^4.6.0
  logger: ^1.1.0
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  dotted_border: ^2.0.0+2
  fluttertoast: ^8.0.9
  rounded_loading_button: ^2.1.0
  uuid: ^3.0.6
  path: ^1.8.2
  provider: ^6.0.3
  flutter_screenutil: ^5.1.1
  dots_indicator: ^2.1.0
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.5
  platform_device_id: ^1.0.1
  pinput: ^2.2.12
  unique_identifier: ^0.3.0
  timeago: ^3.3.0
  fancy_containers: ^0.0.3
  file_picker: ^5.2.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
#  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  flutter_document_picker: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 700
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf
    - family: HelveticaNeueBold
      fonts:
        - asset: fonts/HelveticaNeueBold.ttf




